### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by woodruffw** [sphinx-contrib/autoprogram#14]
Would it be possible to get a new release of `sphinxcontrib-autoprogram` cut and released to PyPI? The current PyPI release is nearly two years behind master.

In particular, it'd be fantastic to be able to use the fix in #11.

Thanks a ton!

**Comment by langston-barrett** [comment]
This will be my first priority after #28.

**Comment by langston-barrett** [comment]
Done, 0.1.7 is on PyPI: https://pypi.org/project/sphinxcontrib-autoprogram/0.1.7/

**Comment by woodruffw** [comment]
![image](https://user-images.githubusercontent.com/3059210/107546650-9a223200-6b9a-11eb-9082-d0d85e669f46.png)

**Comment by woodruffw** [comment]
![](https://ph-files.imgix.net/d224001c-e5b7-4e51-95f6-8d692887d14b?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=772.8813559322034&h=380&fit=max&dpr=2)
