### ISSUE TITLE
Look for a new maintainer

### ISSUE THREAD

**Issue by dahlia** [sphinx-contrib/autoprogram#17]
Since I recently have no much chance to use Python at all, it's getting less motivating me to maintain this project.  If someone who wish maintain this project from now on, I would like to give them all necessary accesses (this repository, PyPI, & RTD.org).  No special prerequisites, but it would be great if them have experience of developing any Sphinx extensions or sending patches to this project.

**Comment by langston-barrett** [comment]
I volunteer to maintain this. I have funding from my work to do so at a low number of hours per month, with a slightly higher initial budget so I can get familiar with the codebase, review initial issues and PRs, etc. We use it on a project I'm on so that's good motivation.

I don't have experience developing a Sphinx extension. I'd be happy to send a PR for #16 if that sounds like a good first step.

**Comment by dahlia** [comment]
@langston-barrett Thank you for helping us!  If you send pull requests, I would be pleased to review your first pull requests to this project, as soon as possible. When you become confident enough about the codebase, I am going to give you all necessary accesses.

**Comment by woodruffw** [comment]
Just bumping this to see whether permissions have been granted to @langston-barrett yet -- I can vouch for their Python, packaging, and project management skills 🙂

**Comment by dahlia** [comment]
I haven't granted anything yet.  If @langston-barrett still would like to be the maintainer, I'm going to grant them permissions as soon as possible.

**Comment by langston-barrett** [comment]
@dahlia Still interested! Thanks.

**Comment by dahlia** [comment]
@langston-barrett First of all, I just invited you as an admin of this repository.  Please check your inbox.  Could you tell me your PyPI & ReadTheDocs.org accounts? I'm going to give you accesses.

**Comment by langston-barrett** [comment]
@dahlia 

PyPI: langston.barrett

ReadTheDocs: siddharthist

Thank you!

**Comment by dahlia** [comment]
I invited you as an owner/maintainer on PyPI & ReadTheDocs.org.  Please check your inbox!

**Comment by langston-barrett** [comment]
Yep, I now have access on both. Thanks @dahlia!
