### ISSUE TITLE
[FYI] autoprogram is now in OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by dcermak** [sphinx-contrib/autoprogram#5]
I have packaged sphinxcontrib-autoprogram for openSUSE, it has been accepted and is now available in Tumbleweed.

As the package maintainer, I am watching this repository and will update it on new releases. If there is something that needs backporting in between releases feel free to ping me.

(Fell free to close this issue, this is just an FYI)

**Comment by dahlia** [comment]
Thanks for your effort! Good to hear that. 👍🏼
